### ISSUE TITLE
Heated Bed Leveling leaves back still slightly unlevel

### ISSUE THREAD

**Issue by jledgett** [Snapmaker/SnapmakerController-IDEX#12]
Many have reported on the user's group (and I have encountered myself) that even after performing the heated bed leveling, the bed is not level (especially front to back).

Can the dev's review this again or add manual fine tuning guidance to the leveling procedure?

**Comment by 747lulu747** [comment]
Hi jledgett, thanks for your proposal.

The bed leveling depends not only on the accuracy of detecting the metal contacts, but also on the accuracy of the thickness of the glass build platform. By default, the thickness of the glass build platform is 5mm. If the glass build platform is too thick or too thin, it will affect the bed leveling effect.

In view of this situation, we have added an interface to set the glass thickness in version V2.5.9, you can actually measure the glass thickness of your J1  and then set the correct glass thickness value of J1.

**Comment by Googliola** [comment]
Hi, thanks for the tip, I did not know.

But thickness adjustment alone does not compensate for differences front to back. What we would need is some kind of leveling mesh.

**Comment by evilC** [comment]
@jledgett @Googliola I just noticed this now, I thought I would comment as to what I think the problem is.  
Certainly on my printer, once you take the glass off the bed, the bed bows - it is higher in the middle than on the left and right edges (Place a known flat object such as a ruler on the bed and see for yourself).  
Seeing as the back point is in the middle, and the left and right points are at the front, this means that when it does the level routine (Which is done when the glass is not on the bed), the left/front and right/front points are lower than they are when the glass is on, which it mis-interprets as the bed not being level
